name: Cognitive Code Analysis

on:
  pull_request:
    paths:
      - '**/*.php'

permissions:
  pull-requests: write
  contents: read

jobs:
  analyse:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: Phauthentic/cca-gh-action@v1
        with:
          install-mode: phar
          post-comment: true
          upload-artifact: false
          emit-annotations: true
          upload-sarif: false
          fail-on-threshold: false
